const WA='5522998217560';
const msg={
 geral:'Olá! Vim pelo site da Beleza Leal e gostaria de conversar com a equipe.',
 emagrecimento:'Olá! Vim pelo site da Beleza Leal e quero entender como funciona o emagrecimento com acompanhamento e o Método BL.',
 mounjaro:'Olá! Vim pelo site da Beleza Leal. Já uso Mounjaro por conta própria e quero entender como posso ter acompanhamento e orientação para seguir com mais segurança.',
 metodo:'Olá! Vim pelo site da Beleza Leal e quero conhecer melhor o Método BL.',
 estetica:'Olá! Vim pelo site da Beleza Leal e quero conversar sobre cuidados estéticos durante meu processo.'
};
const openWA=text=>window.open(`https://wa.me/${WA}?text=${encodeURIComponent(text)}`,'_blank','noopener');
document.querySelectorAll('[data-wa]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openWA(msg[el.dataset.wa]||msg.geral)}));
const header=document.getElementById('header'),progress=document.getElementById('progress');
function onScroll(){header.classList.toggle('scrolled',scrollY>22);const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${h?Math.min(100,scrollY/h*100):0}%`}addEventListener('scroll',onScroll,{passive:true});onScroll();
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.1,rootMargin:'0px 0px -5%'});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
const menu=document.getElementById('menu'),drawer=document.getElementById('drawer');function closeMenu(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');menu.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open');menu.querySelectorAll('span').forEach(x=>x.style.transform='')}
menu.addEventListener('click',()=>{const open=!drawer.classList.contains('open');if(!open)return closeMenu();drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');menu.setAttribute('aria-expanded','true');document.body.classList.add('menu-open');const b=menu.querySelectorAll('span');b[0].style.transform='translateY(4px) rotate(45deg)';b[1].style.transform='translateY(-4px) rotate(-45deg)'});drawer.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
const routeMap={emagrecimento:{section:'metodo',interest:'Emagrecimento com acompanhamento'},mounjaro:{section:'acompanhamento',interest:'Já uso Mounjaro e quero acompanhamento'},metodo:{section:'metodo',interest:'Método BL'},estetica:{section:'estetica',interest:'Outro cuidado estético'}};document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>{const r=routeMap[b.dataset.route];const opt=[...document.getElementById('interest').options].find(o=>o.value===r.interest||o.textContent===r.interest);if(opt)document.getElementById('interest').value=opt.value;document.getElementById(r.section).scrollIntoView({behavior:'smooth',block:'start'})}));
const interest=document.getElementById('interest'),name=document.getElementById('name'),note=document.getElementById('note');document.querySelectorAll('[data-interest]').forEach(b=>b.addEventListener('click',()=>{const opt=[...interest.options].find(o=>o.value===b.dataset.interest||o.textContent===b.dataset.interest);if(opt)interest.value=opt.value;document.getElementById('contato').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>name.focus({preventScroll:true}),500)}));
document.getElementById('form').addEventListener('submit',e=>{e.preventDefault();const n=name.value.trim();if(!n)return name.focus();let text=`Olá! Meu nome é ${n}. Vim pelo site da Beleza Leal e tenho interesse em ${interest.value}.`;if(note.value.trim())text+=`\n\nQueria acrescentar: ${note.value.trim()}`;text+='\n\nGostaria de entender como funciona e qual seria o melhor próximo passo.';openWA(text)});